#!/usr/bin/env bash

printf "[ %s: Subsample paired-end libraries ]\n" \
    "$(date)"

reformat=bin/bbmap/reformat.sh

# shellcheck disable=SC1091
source "src/sh/bash_header"
# shellcheck disable=SC1091
source "src/sh/io_parser"

# make outdir
outdir="$(dirname "${output_fq}")"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# not good, handle parallelisation in ruffus
for i in $(seq 1 "${max_cpus}"); do
    log_file="${outdir}/reformat${i}.log.txt"
    bn=$(basename "${output_fq}" .fastq.gz)
    fq="${outdir}/${bn}${i}.fastq.gz"

    # build the command
    cmd=( "${reformat}"
              "in=${input_fq}"
              "out=${fq}"
              samplereadstarget=1000000 )

    shopt -s extglob
    printf "Final command line: "
    printf "%s " "${cmd[@]//+([[:blank:]])/ }"
    printf "\n"
    shopt -u extglob

    # run job
    srun --ntasks=1 --cpus-per-task=1 --exclusive \
        --output="${log_file}" "${cmd[@]}" &
done
printf "[ %s: Waiting for reformat to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/reformat.METADATA.csv"

printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    reformat version,$("${reformat}" --version 2>&1 | sed '2q;d')
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0


