#!/usr/bin/env bash

printf "[ %s: Run bbduk on paired-end libraries ]\n" \
    "$(date)"

bbduk=bin/bbmap/bbduk.sh

# shellcheck disable=SC1091
source "src/sh/bash_header"
# shellcheck disable=SC1091
source "src/sh/io_parser"

# make outdir
outdir="$(dirname "${output_fq}")"
if [[ ! -d "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# pair the files
for fq_file in "${input_fq[@]}"; do
    bn="$(basename "${fq_file}" .fastq.gz)"
    if grep -q "_R1" <<< "${bn}"; then
        fq_r1="${fq_file}"
    elif grep -q "_R2" <<< "${bn}"; then
        fq_r2="${fq_file}"
    fi
done
printf "\tfq_r1: %s\n\tfq_r2: %s\n" "${fq_r1}" "${fq_r2}"

# build the command
cmd=( "${bbduk}"
        "t=${max_cpus}" 
        "in=${fq_r1}" "in2=${fq_r2}"
        "out=${output_fq}"
        ref=bin/bbmap/resources/adapters.fa
        ktrim=r k=23 mink=11 hdist=1
        "bhist=${outdir}/bhist.txt" "qhist=${outdir}/qhist.txt"
        "gchist=${outdir}/gchist.txt" "aqhist=${outdir}/aqhist.txt"
        "lhist=${outdir}/lhist.txt" "stats=${outdir}/stats.txt"
        tpe tbo )

shopt -s extglob
printf "Final command line: "
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

# run job
log_file="${outdir}/bbduk.log.txt"
srun --ntasks=1 --cpus-per-task="${max_cpus}" --exclusive \
    --output="${log_file}" "${cmd[@]}" &
printf "[ %s: Waiting for bbduk to finish ]\n" "$(date)"
FAIL=0
fail_wait

# log metadata
metadata_file="${outdir}/bbduk.METADATA.csv"

printf "[ %s: Logging metadata ]\n" "$(date)"
printf "metadata_file: %s\n" "${metadata_file}"
cat <<- _EOF_ > "${metadata_file}"
    Script,${0}
    branch,$(git rev-parse --abbrev-ref HEAD)
    hash,$(git rev-parse HEAD)
    date,$(date +%F)
    bbduk version,$("${bbduk}" --version 2>&1 | sed '2q;d')
_EOF_

printf "[ %s: Done ]\n" "$(date)"

exit 0


